### ISSUE TITLE
Should we keep using Elm?

### ISSUE THREAD

**Issue by MattCheely** [purecloudlabs/iframe-coordinator#28]
Pull Request #22 tries to outline the motivation for using Elm in this project. If you haven't already, please take a look at it.  The downside to Elm, of course, is that it's not well known and folks would have to get familiar with it to contribute. 

Here's a list of things I think we get from Elm:

1. Enforced SemVer
2. Bad messages stopped at client boundaries
3. Tools for handling backward message compatibility
4. Generative / property-based testing
5. No runtime exceptions  

I think there are several questions for folks in the group that should help us reach a decision:

- Do you think those features are worth the trade-off of using Elm?
- Are any of those features not particularly valuable?
- Do you  know of js alternatives that can provide the above features?
- If you had to pick up Elm recently, how difficult was it?

**Comment by MattCheely** [comment]
@stormojm Found a repo which could handle points 2 and 3, since it's mostly a clone of Elm's decoders:
https://github.com/ooesili/type-safe-json-decoder

We might have to fork/maintain it if it's not still actively in development by the original creator, but it looks like a pretty reasonable approach. 

I'll say that in terms of learning Elm, it's been a while for me, but it is a pretty simple lanugage. There aren't a whole lot of different kinds of things in it, although the syntax is definitely very different if you're used to JavaScript & Java

**Comment by stormojm** [comment]
So as someone learning Elm, I do think that it isn't that terribly difficult to learn; however, it is still something you have to learn.  This means time invested for anyone who wants to contribute to this.  I would rather make it consistent and have the same tools across our base-common UI portfolio (including styles, apis, build tools, etc).  Any exception or complexity we add increases the friction to adopt our common.

As for the features,
1. Enforce SymVer is nice, but having only this API be enforced doesn't buy us much IMO.  We have all of our components already manually controlled.  Why can't this one also be done by developers?
4. I would hazard a guess that there are similar property testers out there for typescript.  But even still, I don't think our API is that fragile that we absolutely require this level of testing.  I think we can come up with a good set on our own.
5.  Similar argument as 1.  It sure would be nice to have, but the bulk of our code doesn't have this anyways.

**Comment by MattCheely** [comment]
SemVer can be managed by devs, but we're error-prone meat computers. I've been burned by a lot of accidental breaking changes over the years, so I like having a machine in the loop helping me with validation. 

Another possible route for message definition and validation could be JSON Schemas:
https://github.com/bcherny/json-schema-to-typescript
https://github.com/epoberezkin/ajv
https://bitbucket.org/atlassian/json-schema-diff-validator/src/master/

**Comment by stormojm** [comment]
I agree that I don't think this should be in the component library.  Although, its definitely a sibling and some of things will be cross-cutting concerns.

I think I prefer the decoder library as well.  It seems to be a more appropriate tool for the job.  I would like us to maybe spike something with it first though before we 100% commit.   My other hesitation is that it sure seems like it is a unmaintained project (v.0.2.0 and a year old).  As Matt mentioned earlier, we can always fork that, but that brings more maintenance concerns with it.
